### ISSUE TITLE
BaseLibrary 这个库无法获取

### ISSUE THREAD

**Issue by maiglail** [gdutxiaoxu/clipimage#2]
compile project(path: ':submodules:BaseLibrary')   这个库我这边无法获取到,作者应该把这种库直接导入自己的项目中比较稳妥

**Comment by gdutxiaoxu** [comment]
执行 git submodule init, git submodule update, 即可

**Comment by drchengit** [comment]
我直接复制粘贴的，处理完才看见解决方案。。。

**Comment by gdutxiaoxu** [comment]
好的

**Comment by Mr-Zhaozhi** [comment]
没整出来。。
